language: php
php:
  - "5.5"
  - "5.4"
  - "5.3"
  - hhvm

env:
  - DB=mysql
  - DB=postgres

script: php /var/www/tests/travis-ci_testing.php

before_script:
  - cp ./install/Settings* ./
  # Packages installation
  - sudo apt-get update
  - sudo apt-get install -y --force-yes apache2 libapache2-mod-php5 php5-mysql php5-sqlite php5-pgsql
  # Apache webserver configuration
  - echo "Alias /behat $(pwd)/web" | sudo tee -a /etc/apache2/sites-available/default
  - sudo mv * /var/www/
  - sudo a2enmod rewrite
  - sudo /etc/init.d/apache2 restart
  - if [[ "$DB" == "postgres" ]]; then psql -c "DROP DATABASE IF EXISTS hello_world_test;" -U postgres; fi
  - if [[ "$DB" == "postgres" ]]; then psql -c "create database hello_world_test;" -U postgres; fi
  - if [[ "$DB" == "mysql" ]]; then mysql -e "DROP DATABASE IF EXISTS hello_world_test;" -uroot; fi
  - if [[ "$DB" == "mysql" ]]; then mysql -e "create database IF NOT EXISTS hello_world_test;" -uroot; fi
  - if [[ "$DB" == "mysql" ]]; then sudo php /var/www/tests/travis-ci/setup_mysql.php; fi
  - if [[ "$DB" == "postgres" ]]; then sudo php /var/www/tests/travis-ci/setup_pgsql.php; fi
