sudo: required
language: php
dist: xenial

matrix:
  include:
    - php: 7.1
      env:
        - DB=mysql-5.7
        - WEBTESTS=true
        - COVERAGE=true
    - php: 7.3
      env:
        - DB=postgres-9.6
        - WEBTESTS=false
        - COVERAGE=false
      addons:
        postgresql: "9.6"
    - php: 7.1
      env:
        - DB=mariadb-10.3
        - WEBTESTS=false
        - COVERAGE=false
      addons:
        mariadb: '10.3'
    - language: node_js
      node_js:
        - "node"
      php:
      # none
      install:
        - npm install --save-dev jshint stylelint stylelint-order stylelint-config-recommended
      before_script:
      # nothing
      script:
        - node_modules/jshint/bin/jshint .
        - stylelint "**/*.css"
      after_script:
      # nothing
    - language: node_js
      node_js:
        - "node"
      php:
        # none
      install:
        - npm install --save-dev jshint stylelint stylelint-order stylelint-config-recommended
      before_script:
        # nothing
      script:
        - node_modules/jshint/bin/jshint .
        - stylelint "**/*.css"
      after_script:
        # nothing
  fast_finish: true

services:
  - memcached
  - mysql

# Prepare the server (PHP, Apache, PHPUnit, APCu etc)
install:
  - chmod +x tests/travis-ci/*.sh
  - tests/travis-ci/setup-server.sh $DB $TRAVIS_PHP_VERSION $WEBTESTS $COVERAGE
  - tests/travis-ci/setup-selenium.sh $DB $TRAVIS_PHP_VERSION $WEBTESTS $COVERAGE

# Install ElkArte
before_script:
  - tests/travis-ci/setup-elkarte.sh $DB $TRAVIS_PHP_VERSION $WEBTESTS $COVERAGE

# Run the PHPUnit tests
script:
  - /var/www/tests/travis-ci/setup-script.sh $DB $TRAVIS_PHP_VERSION $WEBTESTS $COVERAGE

# Send coverage reports
after_script:
  - /var/www/tests/travis-ci/setup-results.sh $DB $TRAVIS_PHP_VERSION $WEBTESTS $COVERAGE

# Output screen shots, error logs etc
after_failure:
  - /var/www/tests/travis-ci/setup-failure.sh $DB $TRAVIS_PHP_VERSION $WEBTESTS $COVERAGE