sudo: true
language: php

matrix:
  include:
    - php: 5.3
      env: DB=mysql-5.5
    - php: 5.6
      env: DB=mysql-5.6
    - php: 7.0
      env: DB=mysql-5.7
    - php: 5.3
      env: DB=postgres-9.3
    - php: 5.6
      env: DB=postgres-9.3
    - php: 7.0
      env: DB=postgres-9.4
      addons:
        postgresql: "9.4"
    - php: 5.6
      env: DB=mariadb-10.0
      addons:
        mariadb: '10.0'
  fast_finish: true

# Create a Travis memcached enabled environment for the test suite to run in and
# ensure that we test against localhost on Travis-CI.
services: memcached

install:
  - chmod +x tests/travis-ci/setup-server.sh
  - chmod +x tests/travis-ci/setup-selenium.sh
  - tests/travis-ci/setup-server.sh $DB $TRAVIS_PHP_VERSION

# Install ElkArte and memcached
# The `services: memcached` will start a memcached service on localhost
# and on the default port, but in order to test against multiple memcached
# instances we need to spawn a couple more, so we do that during the before
# script
before_script:
  - chmod +x tests/travis-ci/setup-elkarte.sh
  - tests/travis-ci/setup-elkarte.sh $DB $TRAVIS_PHP_VERSION

script:
  - chmod +x /var/www/tests/travis-ci/setup-script.sh
  - /var/www/tests/travis-ci/setup-script.sh $DB $TRAVIS_PHP_VERSION

after_script:
  - chmod +x /var/www/tests/travis-ci/setup-results.sh
  - /var/www/tests/travis-ci/setup-results.sh $DB $TRAVIS_PHP_VERSION

after_failure:
  - chmod +x /var/www/tests/travis-ci/setup-failure.sh
  - /var/www/tests/travis-ci/setup-failure.sh $DB $TRAVIS_PHP_VERSION
