language: php
dist: trusty
os: linix

jobs:
  include:
    - php: 7.3
      env:
        - DB=mysql-5.6
        - WEBTESTS=false
        - COVERAGE=false
    - php: 7.1
      env:
        - DB=postgres-9.5
        - WEBTESTS=false
        - COVERAGE=true
    - php: 5.6
      env:
        - DB=mariadb-10.0
        - WEBTESTS=false
        - COVERAGE=true
      addons:
        mariadb: '10.0'
  fast_finish: true

addons:
  firefox: "50.0"

services:
  memcached

# Prepare the server (PHP, Apache, PHPUnit, APCu etc)
install:
  - chmod +x tests/travis-ci/*.sh
  - tests/travis-ci/setup-server.sh $DB $TRAVIS_PHP_VERSION $WEBTESTS $COVERAGE

# Install ElkArte
before_script:
  - tests/travis-ci/setup-elkarte.sh $DB $TRAVIS_PHP_VERSION $WEBTESTS $COVERAGE

# Run the PHPUnit tests
script:
  - /var/www/tests/travis-ci/setup-script.sh $DB $TRAVIS_PHP_VERSION $WEBTESTS $COVERAGE

# Send coverage reports
after_script:
  - /var/www/tests/travis-ci/setup-results.sh $DB $TRAVIS_PHP_VERSION $WEBTESTS $COVERAGE

# Output screen shots, error logs etc
after_failure:
  - /var/www/tests/travis-ci/setup-failure.sh $DB $TRAVIS_PHP_VERSION $WEBTESTS $COVERAGE
